meta: fix clippy warning that should not happen
This commit is separate from the feature because probably
the route code is the commit c0f7de3d6c3d679afa1e3e47f33ace1da687b2d2
where the `async_payments` cfg is not set.

Fixing the following warning

error: associated function `features_unchecked` is never used
   --> lightning/src/offers/invoice_macros.rs:91:2
    |
91  | /     pub(crate) fn features_unchecked(
92  | |         $($self_mut)* $self: $self_type, features: Bolt12InvoiceFeatures
93  | |     ) -> $return_type {
94  | |         $invoice_fields.features = features;
95  | |         $return_value
96  | |     }
    | |_____^
    |
   ::: lightning/src/offers/static_invoice.rs:186:5
    |
186 |       invoice_builder_methods_test_common!(self, Self, self.invoice, Self, self, mut);
    |       ------------------------------------------------------------------------------- in this macro invocation
    |
    = note: `-D dead-code` implied by `-D warnings`
    = note: this error originates in the macro `invoice_builder_methods_test_common` (in Nightly builds, run with -Z macro-backtrace for more info)

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>