Pin ahash version that supports LDK's MSRV.
Currently some builds fail because of
```
error: package `ahash v0.8.8` cannot be built because it requires rustc 1.72.0 or newer, while the currently active rustc version is 1.63.0
```

Downgrading it to v0.8.7 solves the issue.