Implement std::error::Error for SocketParseError
SocketParseError does not implement std Error which means it can't be
used in standard ways like combining ? and anyhow.

This commit implements std::error::Error for SocketParseError

Hide the std::error::Error for SocketAddressParseError implementation
behind the "std" feature since it relies on the standard library.